#!/usr/bin/env python
import sys

sys.stdout.write("restore simulation for: ")

if (len(sys.argv) > 1):
    sys.argv.pop(0)
    for item in sys.argv:
        val = str(item).encode("ascii")
        if val:
            sys.stdout.write(val)
else:
 sys.stdout.write("no data to restore...")