version: '3'
services:
  link:
      build:
        context: .
      restart: always
      ports:
          - 80:80
          - 443:443
          - 8765:8765
      volumes:
          - ./apps:/opt/server/apps
      environment:
          - CLOUD=false
          - DB=db/dev
          - SSL_PRIVATE_KEY=/opt/server/certs/privkey.pem
          - SSL_CERTIFICATE=/opt/server/certs/fullchain.pem

volumes:
  apps: 