version: '3'
services:
  link:
      build:
        context: .
        args:
            apps: https://github.com/lantern-works/lantern-apps
      restart: always
      ports:
          - 80:80
          - 443:443
          - 8765:8765
      environment:
          - CLOUD=false
          - DB=db/stage
          - SSL_PRIVATE_KEY=/opt/server/certs/privkey.pem
          - SSL_CERTIFICATE=/opt/server/certs/fullchain.pem
