app_server:
    build: .
    restart: always
    ports:
        - 80:80
        - 443:443
    environment:
        - CLOUD=false
        - DB=db/docker
    volumes:
        - ./web/db:/opt/lantern/db
        - ./web/public:/opt/lantern/public