app_server:
    build: .
    restart: always
    ports:
        - 80:80
        - 443:443
    environment:
        - CLOUD=false
        - DEV=true
        - MAP_DB_PEER=https://37bd9e99-2780-4965-8da8-b6b1ebb682bc-bluemix.cloudant.com/lantern-us-maps
        - LNT_DB_PEER=https://37bd9e99-2780-4965-8da8-b6b1ebb682bc-bluemix.cloudant.com/lantern-us-demo
    volumes:
        - ./db:/opt/lantern/db
        - ./public:/opt/lantern/public