#!/usr/bin/env python
import sys

if (len(sys.argv) > 1):
    sys.argv.pop(0)
    for item in sys.argv:
        val =  str(item).encode("ascii")
        if val:
            sys.stdout.write(val)
else:
    sys.stdout.write("no message to queue for outbox...")