#!/usr/bin/env python
import sys
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

if (len(sys.argv) > 1):
    sys.argv.pop(0)
    for item in sys.argv:
        val =  str(item).encode("ascii")
        print("adding to outbox: " + val)
        r = requests.put("https://localhost:9443/api/outbox", verify=False, json={"message": val})
        print (r.text)
 
else:
    print("no message to queue for outbox...")